export const abilities = [
	{
		name: 'html',
		imageUrl: '/icons/html.svg',
		level: 'Avanzado',
		type: 'Frontend',
	},
	{
		name: 'css',
		level: 'Intermedio',
		imageUrl: '/icons/css.svg',
		type: 'Frontend',
	},
	{
		name: 'JavaScript',
		level: 'Avanzado',
		imageUrl: '/icons/javascript.svg',
		type: 'Frontend',
	},
	{
		name: 'TypeScript',
		level: 'Avanzado',
		imageUrl: '/icons/typescript.svg',
		type: 'Frontend',
	},
	{
		name: 'React',
		level: 'Avanzado',
		imageUrl: '/icons/react.svg',
		type: 'Frontend',
	},
	{
		name: 'Nextjs',
		level: 'Intermedio',
		imageUrl: '/icons/nextjs.svg',
		type: 'Frontend',
	},
	{
		name: 'Styled Components',
		level: 'Intermedio',
		imageUrl: '/icons/styled-components.png',
		type: 'Frontend',
	},
	{
		name: 'Bootstrap',
		level: 'Intermedio',
		imageUrl: '/icons/bootstrap.svg',
		type: 'Frontend',
	},
	{
		name: 'Sass',
		level: 'Intermedio',
		imageUrl: '/icons/sass.png',
		type: 'Frontend',
	},
	{
		name: 'Tailwind Css',
		level: 'Intermedio',
		imageUrl: '/icons/tailwind-css.png',
		type: 'Frontend',
	},

	{
		name: 'Nodejs',
		level: 'Avanzado',
		imageUrl: '/icons/nodejs.svg',
		type: 'Backend',
	},
	{
		name: 'PHP',
		level: 'Intermedio',
		imageUrl: '/icons/php.svg',
		type: 'Backend',
	},
	{
		name: 'Laravel',
		level: 'Intermedio',
		imageUrl: '/icons/laravel.png',
		type: 'Backend',
	},
	{
		name: 'GraphQL',
		level: 'Básico',
		imageUrl: '/icons/graphql.svg',
		type: 'Backend',
	},
	{
		name: 'Express',
		level: 'Intermedio',
		imageUrl: '/icons/express.png',
		type: 'Backend',
	},
	{
		name: 'MySQL',
		level: 'Intermedio',
		imageUrl: '/icons/mysql.png',
		type: 'Database',
	},
	{
		name: 'MongoDB',
		level: 'Intermedio',
		imageUrl: '/icons/mongodb.svg',
		type: 'Database',
	},
	{
		name: 'TypeORM',
		level: 'Básico',
		imageUrl: '/icons/typeorm.png',
		type: 'Database',
	},
];
