export const projects = [
	{
		title: 'Portafolio',
		description: 'Proyecto personal para mostrar mis habilidades y proyectos. Aprendi a utilizar mejor Docker por lo que el proyecto esta alojado en un contenedor de Docker.',
		imageUrl: '/imgs/coding.jpg',
		githubUrl: 'https://juancode.vercel.app/',
		websiteUrl: 'https://juancode.vercel.app/',
		technologies: [
			'Nextjs',
			'React',
			'TypeScript',
			'Tailwind Css',
			'MongoDB',
			'Mongoose',
			'Docker',
			'Axios',
		],
		date: '2021-08-01',
	},
	{
		title: 'Portafolio 2',
		description: 'Portafolio personal',
		imageUrl: '/imgs/coding.jpg',
		githubUrl: 'https://juancode.vercel.app/',
		websiteUrl: 'https://juancode.vercel.app/',
		technologies: [
			'React',
			'Nextjs',
			'Styled Components',
			'Bootstrap',
			'SASS',
			'Tailwind Css',
			'TypeScript',
		],
		date: '2021-08-01',
	},

	{
		title: 'Portafolio 3',
		description: 'Portafolio personal',
		imageUrl: '/imgs/coding.jpg',
		githubUrl: 'https://juancode.vercel.app/',
		websiteUrl: 'https://juancode.vercel.app/',
		technologies: [
			'React',
			'Nextjs',
			'Styled Components',
			'Bootstrap',
			'SASS',
			'Tailwind Css',
			'TypeScript',
		],
		date: '2021-08-01',
	},
];
